### ISSUE TITLE
Pass OTS

### ISSUE THREAD

**Issue by davelab6** [NDISCOVER/Arima-Font#1]
The Madurai files are ok, but the Koshi files fail https://github.com/khaledhosny/ots as follows

```
~/src/FONTQ/github.com/NDISCOVER/Arima-Font/ttf/ArimaKoshi$ for i in `ls -1 *ttf`; do echo $i; ot-sanitise $i; done
ArimaKoshi-Black.ttf
ERROR at src/cmap.cc:186 (ParseFormat4)
ERROR: cmap: Out of order end range (3415 <= 3415)
ERROR at src/cmap.cc:771 (ots_cmap_parse)
ERROR: cmap: Failed to parse format 4 cmap subtable 0
ERROR at src/ots.cc:669 (ProcessGeneric)
Failed to sanitise file!
ArimaKoshi-Bold.ttf
ERROR at src/cmap.cc:186 (ParseFormat4)
ERROR: cmap: Out of order end range (3415 <= 3415)
ERROR at src/cmap.cc:771 (ots_cmap_parse)
ERROR: cmap: Failed to parse format 4 cmap subtable 0
ERROR at src/ots.cc:669 (ProcessGeneric)
Failed to sanitise file!
ArimaKoshi-ExtraBold.ttf
ERROR at src/cmap.cc:186 (ParseFormat4)
ERROR: cmap: Out of order end range (3415 <= 3415)
ERROR at src/cmap.cc:771 (ots_cmap_parse)
ERROR: cmap: Failed to parse format 4 cmap subtable 0
ERROR at src/ots.cc:669 (ProcessGeneric)
Failed to sanitise file!
ArimaKoshi-ExtraLigth.ttf
ERROR at src/cmap.cc:186 (ParseFormat4)
ERROR: cmap: Out of order end range (3415 <= 3415)
ERROR at src/cmap.cc:771 (ots_cmap_parse)
ERROR: cmap: Failed to parse format 4 cmap subtable 0
ERROR at src/ots.cc:669 (ProcessGeneric)
Failed to sanitise file!
ArimaKoshi-Light.ttf
ERROR at src/cmap.cc:186 (ParseFormat4)
ERROR: cmap: Out of order end range (3415 <= 3415)
ERROR at src/cmap.cc:771 (ots_cmap_parse)
ERROR: cmap: Failed to parse format 4 cmap subtable 0
ERROR at src/ots.cc:669 (ProcessGeneric)
Failed to sanitise file!
ArimaKoshi-Medium.ttf
ERROR at src/cmap.cc:186 (ParseFormat4)
ERROR: cmap: Out of order end range (3415 <= 3415)
ERROR at src/cmap.cc:771 (ots_cmap_parse)
ERROR: cmap: Failed to parse format 4 cmap subtable 0
ERROR at src/ots.cc:669 (ProcessGeneric)
Failed to sanitise file!
ArimaKoshi-Regular.ttf
ERROR at src/cmap.cc:186 (ParseFormat4)
ERROR: cmap: Out of order end range (3415 <= 3415)
ERROR at src/cmap.cc:771 (ots_cmap_parse)
ERROR: cmap: Failed to parse format 4 cmap subtable 0
ERROR at src/ots.cc:669 (ProcessGeneric)
Failed to sanitise file!
ArimaKoshi-Thin.ttf
ERROR at src/cmap.cc:186 (ParseFormat4)
ERROR: cmap: Out of order end range (3415 <= 3415)
ERROR at src/cmap.cc:771 (ots_cmap_parse)
ERROR: cmap: Failed to parse format 4 cmap subtable 0
ERROR at src/ots.cc:669 (ProcessGeneric)
Failed to sanitise file!
```

**Comment by NDISCOVER** [comment]
Hey Dave, we are not familiar with the semantics of this report. How can we correct this?

**Comment by davelab6** [comment]
Something became messed up in the CMAP table when the files were compiled. How did you build them?

**Comment by NDISCOVER** [comment]
The CMAP is build automatically by glyphs makeOTF. We are working on this at the moment.

**Comment by davelab6** [comment]
Post in glyphs forum?

**Comment by NDISCOVER** [comment]
We talked with Georg directly. The error was due to a wrongly spelled Malayalam Mark. 
It should be solved now, but we didn't do the the sanitise (couldn't install it for some reason). 
Can you do it again?

**Comment by davelab6** [comment]
I documented how to install stuff in https://github.com/davelab6/dotfiles/blob/master/Mac.md#font-toolbox

The new TTFs look good!

```
$ cd ~/src/github.com/NDSICOVER/Arima-Font/ttf ;
$ for font in `find . -name \*ttf -print`; do echo $font; ot-sanitise $font; done
./ArimaKoshi/ArimaKoshi-Black.ttf
./ArimaKoshi/ArimaKoshi-Bold.ttf
./ArimaKoshi/ArimaKoshi-ExtraBold.ttf
./ArimaKoshi/ArimaKoshi-ExtraLight.ttf
./ArimaKoshi/ArimaKoshi-Light.ttf
./ArimaKoshi/ArimaKoshi-Medium.ttf
./ArimaKoshi/ArimaKoshi-Regular.ttf
./ArimaKoshi/ArimaKoshi-Thin.ttf
./ArimaMadurai/ArimaMadurai-Black.ttf
./ArimaMadurai/ArimaMadurai-Bold.ttf
./ArimaMadurai/ArimaMadurai-ExtraBold.ttf
./ArimaMadurai/ArimaMadurai-ExtraLight.ttf
./ArimaMadurai/ArimaMadurai-Light.ttf
./ArimaMadurai/ArimaMadurai-Medium.ttf
./ArimaMadurai/ArimaMadurai-Regular.ttf
./ArimaMadurai/ArimaMadurai-Thin.ttf
```

**Comment by davelab6** [comment]
Arf, when I regenerated them from source, they failed again, same as before.

**Comment by NDISCOVER** [comment]
“there is an error in the GlyphData. The production name of
the aulengthmark-malayalam and rakar-malayalam were switched.
You need to fix this either in a custom glyphdata.xml or directly in the
file. Select the aulengthmark-malayalam, hit cmd+opt+I, check the button at
the production name and assign uni0D57 as value. The same for the
rakar-malayalam, assign uni0D4D0D30.”

**Comment by davelab6** [comment]
On 19 February 2016 at 10:40, NDISCOVER notifications@github.com wrote:

> “there is an error in the GlyphData. The production name of
> the aulengthmark-malayalam and rakar-malayalam were switched.
> You need to fix this either in a custom glyphdata.xml or directly in the
> file. Select the aulengthmark-malayalam, hit cmd+opt+I, check the button at
> the production name and assign uni0D57 as value. The same for the
> rakar-malayalam, assign uni0D4D0D30.”

Okay, I'll do this and send a PR

**Comment by davelab6** [comment]
I think what happened is that you used an older version of Glyphs. I'm using `Version 2.3b (848)`

**Comment by NDISCOVER** [comment]
I'm not using cutting edge versions. But I can edit it then.

**Comment by davelab6** [comment]
Can you export this? :( 

<img width="420" alt="screen shot 2016-02-19 at 11 05 01" src="https://cloud.githubusercontent.com/assets/261579/13180979/c38f8c46-d6f8-11e5-9c82-12fb8b1a72c0.png">
