### ISSUE TITLE
Add ArimaMadurai PS hinting

### ISSUE THREAD

**Issue by davelab6** [NDISCOVER/Arima-Font#11]
ArimaKochi has PS hinting in Font Info/Masters but ArimaMadurai does not.

**Comment by NDISCOVER** [comment]
Where? They appear to have the same parameters

**Comment by davelab6** [comment]
The stems inputs, here:

<img width="1680" alt="screen shot 2016-02-19 at 08 38 23" src="https://cloud.githubusercontent.com/assets/261579/13176972/2bfc01ca-d6e4-11e5-8e35-84ad46645c93.png">

**Comment by NDISCOVER** [comment]
Done.
Exported new ttf and otf as this values influence hinting

**Comment by davelab6** [comment]
https://github.com/NDISCOVER/Arima-Font/commit/47830d7a21fe2e699d21b78dc67951d9c6b3f99d Nice :)
