### ISSUE TITLE
Composition issues for Malayalam

### ISSUE THREAD

**Issue by yanone** [NDISCOVER/Arima-Font#29]
I'm commissioned with onboarding Arima to Google Fonts, and found a few composition issues with the Malayalam. Each of the three images is comparing Arima to Baloo and Noto.

<img width="1123" alt="Bildschirmfoto 2022-01-21 um 16 02 54" src="https://user-images.githubusercontent.com/175386/150550370-48ee4761-43a9-435e-a96f-b6d9ef3816a8.png">
<img width="682" alt="Bildschirmfoto 2022-01-21 um 16 02 24" src="https://user-images.githubusercontent.com/175386/150550384-64cbeae8-167e-4343-89c1-512acfc3d97a.png">
<img width="1264" alt="Bildschirmfoto 2022-01-21 um 16 01 24" src="https://user-images.githubusercontent.com/175386/150550390-114f8064-80c9-4b65-bfef-d5768868ee30.png">

I suspect that the fonts are missing feature code, because it does seem to contain the two glyphs that I see in the lower two fonts:
<img width="155" alt="Bildschirmfoto 2022-01-21 um 16 09 36" src="https://user-images.githubusercontent.com/175386/150550743-8d77fb3e-1f50-45b3-b3e1-7fea63f7871e.png">

I am no expert in these languages and would therefore like to ask for clarification or the development of changes on your side. Thank you.

**Comment by NDISCOVER** [comment]
Hi Yanone

I am in the process of correcting issues with the Malayalam and Tamil, I have analysis from native type designers already.

Maybe we should wait for me to complete the review and only then merge the files, does that sound good?
I think it is best.

Thank you!

**Comment by yanone** [comment]
Sure, please make your changes and let me know when you're done. Thank you.

**Comment by NDISCOVER** [comment]
Hi @yanone the scripts are updated!

**Comment by yanone** [comment]
Thank you, I'll take a look soon

**Comment by santhoshtr** [comment]
The fixes are not present in Google fonts yet. Would it be feasible to update the fonts there?
cc @davelab6

**Comment by yanone** [comment]
I’ll take a look at this, as I've onboarded the existing version of Arima. Which fixes do you mean?

**Comment by santhoshtr** [comment]
ന്ത്ര്യ rendering:

![image](https://user-images.githubusercontent.com/161672/188487644-660cb1a4-468e-479d-9139-8f607d0ab203.png)
![image](https://user-images.githubusercontent.com/161672/188487774-6f14ec1e-13ca-4018-bb31-75250f611b7e.png)

ൻ്റ rendering

![image](https://user-images.githubusercontent.com/161672/188488090-b812c23d-3258-43f7-af47-3f58873e4655.png)
![image](https://user-images.githubusercontent.com/161672/188488120-2d034c67-d47a-4eac-b694-672453b371cd.png)
