### ISSUE TITLE
Reported Malayalam rendering issue

### ISSUE THREAD

**Issue by yanone** [NDISCOVER/Arima-Font#34]
Over in https://github.com/NDISCOVER/Arima-Font/issues/29, an issue which I can't reopen, user [santhoshtr](https://github.com/santhoshtr) has reported rendering issues of Arima with the two strings ന്ത്ര്യ and ൻ്റ.

The version of the font currently served by Google is identical to the latest version of the font binary here in the repository. Since the font binary got last changed *after* the source, I must conclude that this issue hasn’t been addressed in the source.

Please take a look and see if the rendering issue can be fixed. Thank you.

**Comment by NDISCOVER** [comment]
This issue is now fixed in the last update
