### ISSUE TITLE
Malayalam shaping issues, revisited

### ISSUE THREAD

**Issue by yanone** [NDISCOVER/Arima-Font#36]
Hello,
while reviewing the latest Arima font, we've discovered a significant amount of shaping issues where the latest font differs from both the previous Arima as hosted on GF as well as reference fonts (Noto Sans and Serif).

Each of these words contain at least one situation where the shaping differs (situation in first word is highlighted): ഇഷ്ടമല്ലസ്നേഹമാണ് പരസ്പരം സ്ത്രീകള്‍ അപ്പൊസ്തലന്മാരെന്നു സാദ്ധ്യമല്ലഎല്ലായ്പ്പോഴുംഅവന്‍റെമേല്‍കല്ലറയിലേക്കുസ്ഫടികം വിഡ്ഢിയെപ്പോലെ ചെയ്തതിനെക്കാള്‍ പ്രശ്നങ്ങള്‍ കുഷ്ഠരോഗിയായ സ്വപ്നത്തില്‍ നമസ്കരിക്കും പ്രാപ്തരാക്കി വിധിയ്ക്കുന്നു അത്ഭുതസ്തബ്ധരായി ദൈവത്തിന്റെ അബ്രഹാമിന്‍റെഎന്നിലേല്പിച്ച പരിച്ഛേദനയ്ക്കു പ്രതിജ്ഞചെയ്തു

None of us is an expert in Malayalam and therefore we need to refer the issue back to you: Is the new shaping legitimate? We doubt it when comparing to Noto. Please go through every of the above posted words to judge.

The previous shaping issue (ന്ത്ര്യ and ൻ്റ) looks fixed indeed. (First in below's screenshot)

The screenshot shows top to bottom: 
* Latest Arima from the repo (I also tried exporting it directly from Glyphs like you did to make sure our toolchain didn't mess up, but same result)
* Arima as currently hosted on Google Fonts
* Notos

<img width="2180" alt="Bildschirm­foto 2023-02-21 um 14 28 01" src="https://user-images.githubusercontent.com/175386/220358431-f58054ff-6589-4acd-bb6b-57abac823910.png">

Thank you for looking into this.

**Comment by NDISCOVER** [comment]
Hi @yanone 
I checked and also asked my Malayalam consultant and everything is looking good. 
Arima has a different set of conjuncts than Noto, actually the exact conjuncts required as in the Malayalam script reform issued by the government in 2022, so it is normal to encounter different renderings of the same character strings in Noto, as before the reform the amount of conjuncts to be in a font were (more or less) up to the designer.
So it all seems to be good.
Thank you!

**Comment by NDISCOVER** [comment]
Maybe Noto will be updated in the near future to account for this new script reform

**Comment by yanone** [comment]
Thank you. Closing this.
