### ISSUE TITLE
Samples sources + updated

### ISSUE THREAD

**Issue by davelab6** [NDISCOVER/Arima-Font#9]
- [ ] https://github.com/davelab6/Arima-Font/tree/master/SAMPLES has binaries but no source files
- [ ] they are out of date and should be regenerated on the next release

**Comment by NDISCOVER** [comment]
This are not exhaustive samples, not sure if it is really needed to have a
pdf with all the characters. What we can do is just a simple PDF sample
that roughly covers the features and the languages supported.

**Comment by davelab6** [comment]
Sure, I'm not suggesting anything other than adding the source files, and
recompiling the PDFs with the latest fonts.

**Comment by NDISCOVER** [comment]
Done
